name: Build differential documents and deploy them on GitHub Releases
on:
  push:

jobs:
  Run-LaTeXdiff:
    runs-on: ubuntu-latest
    steps:
      - name: Make ImageMagik permissive
        run: sudo sed -i 's/rights=".*"/rights="all"/' /etc/ImageMagick-6/policy.xml
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch tags
        shell: bash
        run: git fetch --tags -f
      - name: Compile differential documents
        uses: DanySK/auto-latexdiff@master
      - name: Autotag
        uses: DanySK/semver-autotag-action@master
      - name: Deploy
        if: ${{ startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=$(git describe --tags --exact-match HEAD)
          hub release create -m "$(git tag -l --format='%(contents)' "$TAG")" "$TAG" || true
          while IFS= read -r file; do
            pdf="${file%.*}.pdf"
            echo "Delivering file $pdf"
            gh release upload "$TAG" "$pdf" --clobber
          done <"auto-latexdiff.log"
